# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3d384be7562a1509738b0ed27a7796061606146244758fb20d0850fb46d03f6db3171a7a902889b719685ef410c3edc4468da3027899eba2c6fdba373f2196e

test:
  secret_key_base: 22972c86da85edbb15e0d579ddf7a4220a40020c14055d06eb15c32d5271984e201ba0a7e37129585f09b524ab8b759887898a8d2a2926ba16af937b0b556909

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
